services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbuserpwd
      - POSTGRES_DB=movies
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
