### Create new Movie
POST {{apiBase}}/api/movies
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "The Matrix Revolutions",
  "yearOfRelease": 2003,
  "genres": [
    "fiction"
  ]
}

### Create new Movie
POST {{apiBase}}/api/movies
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "The Lord of the Rings: The Fellowship of the Ring",
  "yearOfRelease": 2001,
  "genres": [
    "adventure"
  ]
}

### Get Movie By Id
GET {{apiBase}}/api/movies/23020fff-ac63-45b8-8bfb-40ff5f87aee7
Authorization: Bearer {{token}}
Accept: application/application/json

### Get Movie By Slug
GET {{apiBase}}/api/movies/the-matrix-1999
Authorization: Bearer {{token}}
Accept: application/application/json

### Get All Movies
GET {{apiBase}}/api/movies
Authorization: Bearer {{token}}
Accept: application/application/json

### Update new Movie
PUT {{apiBase}}/api/movies/23020fff-ac63-45b8-8bfb-40ff5f87aee7
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "The Matrix",
  "yearOfRelease": 1999,
  "genres": [
    "fiction", "action"
  ]
}

### Delete Movie
DELETE {{apiBase}}/api/movies/7b1872a7-c6c9-4803-b002-28b587e1be81
Authorization: Bearer {{token}}

